name: Mac
on: 
  workflow_dispatch:
jobs:
  build:
    name: Mac
    runs-on: macos-15-intel
    
    steps:                 
    - name: step 1
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      run: |
          curl -s -o start.sh -L "https://raw.githubusercontent.com/JohnnyNetsec/github-vm/main/mac/start.sh"
          chmod +x start.sh
          bash start.sh "$NGROK_AUTH_TOKEN"
          
    - name: step 2
      run: |
         chmod +x login.sh
         bash login.sh
         
    - name: MacOS System running...
      uses: mxschmitt/action-tmate@v2
